sudo: required
service:
   - docker

before_install:
   - docker build -t stonedpanda/firstciimage -f dockerfile.dev .

script:
   - docker run -e CI=true stonedpanda/firstciimage npm run test -- -- coverage
