sudo: required
service:
   - docker

before_install:
   - docker build -t stonedpanda/udemy-images:part1 -f dockerfile.dev .

script:
   - docker run -e CI=true stonedpanda/udemy-images:part1 npm run test -- -- coverage
